name: Consolidate and Convert Document

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/core:2.9
        with:
          args: "--standalone --output=output/result.docx sections/title.txt"
      # - uses: actions/checkout@master
      # - name: Copy File
      # - uses: canastro/copy-file-action@master
      #     with:
      #       source: "output/result.docx"
      #       target: "result.docx" 
      # - uses: actions/upload-artifact@master
      #   with:
      #     name: output
      #     path: output
      - name: setup git config username
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add output/result.docx
          git commit -m "New version of output document"
          git push origin main
