name: Consolidate and Convert Document

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "--standalone --output=index.html title.txt"
#          args: "-o /github/workspace/blueprint.docx /github/workspace/title.txt"
