name: Consolidate and Convert Document

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # make an oobe version
      - uses: docker://pandoc/core:2.9
        with:
          args: "--standalone \
          --output=oobeBlueprint.docx \
          --reference-doc=templates/oobeTemplate.docx \
          sections/11.IdentityAndAccessManagement.md \
          sections/12.Security.md \
          sections/13.ClientConfiguration.md \
          sections/14.BackupAndOperationalManagement.md \
          sections/15.SystemAdministration.md \
          sections/16.RBAC.md"
      # make a DTA version
      - uses: docker://pandoc/core:2.9
        with:
          args: "--standalone \
          --output=DTABlueprint.docx \
          --reference-doc=templates/DTATemplate.docx 
          sections/11.IdentityAndAccessManagement.md \
          sections/12.Security.md \
          sections/13.ClientConfiguration.md \
          sections/14.BackupAndOperationalManagement.md \
          sections/15.SystemAdministration.md \
          sections/16.RBAC.md"
      - name: setup git config username
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add .
          git commit -m "New version of output document"
          git push
